config/routes.rb
Rails.application.routes.draw do
  root to: 'searchs#index'#"/"に対するルーティング
  get 'searchs_url', to: 'searchs#index'
  get 'youtube', to: 'searchs#csv'
  resources :searchs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 include ApiHelper


end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def index
   if params[:param_page].present?
     session[:filter]=params[:search][:filter]
     youtube_data = find_videos(params[:search][:keyword],params[:search][:row_count],params[:search][:order],params[:search][:publishedAfter])
     @videos =Kaminari.paginate_array(hash_video(youtube_data)).page(params[:page]).per(10)
   else
   session[:keyword]=nil
   session[:row_count]=nil
   session[:order]=nil
   session[:publishedAfter]=nil
   session[:filter]=nil
   session[:cont]=nil
   session[:video_hidden]=nil
 end
  end


  def create
    if params[:search][:row_count]=="" || params[:search][:keyword]==""
      flash[:danger] = 'キーワード及び検索件数を入力してください'
    else
      session[:filter]=params[:search][:filter]
      youtube_data = find_videos(params[:search][:keyword],params[:search][:row_count],params[:search][:order],params[:search][:publishedAfter])
      @videos =Kaminari.paginate_array(hash_video(youtube_data)).page(params[:page]).per(10)
    end
      session[:keyword]=params[:search][:keyword]
      session[:row_count]=params[:search][:row_count]
      session[:order]=params[:search][:order]
      session[:publishedAfter]=params[:search][:publishedAfter]
      if params[:search][:video_hidden]=='1'
        session[:video_hidden]=true
      else
        session[:video_hidden]=false
      end
    render :index
  end
  
  def csv
    if session[:row_count].present? || session[:keyword].present? || session[:row_count]!="" || session[:keyword]!=""
      youtube_data = find_videos(session[:keyword],session[:row_count],session[:order],session[:publishedAfter])
      @videos =hash_video(youtube_data)
    end
      render :index
  end

end

app/helpers/api_helper.rb
module ApiHelper
require 'google/apis/youtube_v3'
require 'active_support/all'
require 'date'

GOOGLE_API_KEY=ENV['GOOGLE_API_KEY']

def find_videos(keyword,row_count,order,publishedAfter, before: Time.now)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = GOOGLE_API_KEY
    next_page_token = nil
    after = date(publishedAfter)
    opt = {
      q: keyword,
      type: 'video',
      max_results: row_count.to_i,
      order: order,
    page_token: next_page_token,
    published_after: after.iso8601,
    published_before: before.iso8601
  }
    result =service.list_searches(:snippet, opt)
    result
  end
  
  def date(publishedAfter)
    case publishedAfter
    when '1.months.ago' then
      after =1.months.ago
    when '3.months.ago' then
      after =3.months.ago
    when '6.months.ago' then
      after =6.months.ago
    when '1.years.ago' then
      after =1.years.ago
    when '3.years.ago' then
      after =3.years.ago
    else 
      after =5.years.ago
    end
    after
  end 
  
  def hash_video(results)
    videos = []
      sum =0
      results.items.each do |item|
        video_statics = videos(item.id.video_id)
        channel_statics= channels(item.snippet.channel_id)
        video_id = item.id.video_id
        title = item.snippet.title
        published_at=item.snippet.published_at
        play_count =video_statics.items.first.statistics.view_count
        channel_title =channel_statics.items.first.snippet.title
        subscriber_count =channel_statics.items.first.statistics.subscriber_count
        play_rate =(play_count.to_f/subscriber_count.to_i)*100
        if(session[:filter].nil? || session[:filter]=="" || play_rate >= (session[:filter].to_i))
          hash = {}
          hash["video_id"] = video_id
          hash["title"] = title
          hash["published_at"] = published_at.to_date
          hash["view_count"] = play_count
          hash["channel_title"] = channel_title
          hash["subscriber_count"] = subscriber_count
          hash["play_rate"] = play_rate.round(3)
          videos << hash
          sum =sum+1
        end
      end 
      session[:cont]=sum
      videos
  end
  
  def videos(video_ids)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = GOOGLE_API_KEY
     opt = {
       id: video_ids
     }
    videos = service.list_videos(:statistics, opt)
  end
  
  def channels(channel_ids)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = GOOGLE_API_KEY
     opt = {
       id: channel_ids
     }
    channels = service.list_channels("statistics,snippet", opt)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    require 'google/apis/youtube_v3'
require 'active_support/all'

GOOGLE_API_KEY="AIzaSyDCcTL6oBWoM1lbzfFB9vSRivSeEDKaKoA"

def find_videos(keyword, after: 1.months.ago, before: Time.now)
  service = Google::Apis::YoutubeV3::YouTubeService.new
  service.key = GOOGLE_API_KEY

  next_page_token = nil
  begin
    opt = {
      q: keyword,
      type: 'video',
      max_results: 10,
      order: :date,
      page_token: next_page_token,
      published_after: after.iso8601,
      published_before: before.iso8601
    }
    return results = service.list_searches(:snippet, opt)
    results.items.each do |item|
      snippet = item.snippet
      puts "\"#{snippet.title}\" by #{snippet.channel_title} (#{snippet.published_at})"
    end

    next_page_token = results.next_page_token
  end while next_page_token.present?
end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>YoutubeApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/searchs/index.html.erb
<h1>Youtube検索</h1>

  <%= form_with(url: searchs_url, scope: :search, local: true) do |f| %>
  <label>キーワード　　：</label><%= f.text_field :keyword,:value =>session[:keyword]%><br>
  <label>検索件数(上位) ：</label><%= f.number_field :row_count,:value =>session[:row_count], min:1,max:30,step:1%> <br>
  <label>並び順　　　　：</label><%= f.select :order,[['日付','date'],['関連度','relevance'],['視聴回数','viewCount'],['評価','rating']],{selected: session[:order]}%> <br>
  <label>投稿期間　　　：</label><%= f.select :publishedAfter,[['1ヵ月前','1.months.ago'],['3ヵ月前','3.months.ago'],['6ヵ月前','6.months.ago'],['1年前','1.years.ago'],['3年前','3.years.ago']],{selected: session[:publishedAfter]}%> <br>
  <label>フィルター　　：</label><%= f.number_field :filter,:value =>session[:filter], min:1,max:1000%> % 以上　(再生数/チャンネル登録数)<br>
  <label>動画の非表示　：</label><%= f.check_box :video_hidden,{checked: session[:video_hidden]}%><br>
<%= f.submit '検索' , class: "mt-1 mb-3"%>
<%end%>
<%= link_to "CSV出力", youtube_path(format: :csv), class: "btn btn-primary mb-3" %>
<%if @videos.present? %>
  <h3 class="mb-3 border-bottom border-primary">出力件数：<%=session[:cont]%> / <%=session[:row_count]%> 件</h3>
  <% @videos.each do |video| %>
  <div class="mb-3 border-bottom border-primary">
    <label class ="bold">タイトル：</label><label><%= video["title"] %></label><br>
    <label class ="bold">投稿日：</label><label><%= video["published_at"] %>　</label>
    <label class ="bold">再生数：</label><label><%=video["view_count"]%>回　</label>
    <label class ="bold">再生率：</label><label><%=video["play_rate"]%>％</label><br>
    <%if session[:video_hidden] == false%>
      <div ><iframe width="560" height="315" src="https://www.youtube.com/embed/<%= video["video_id"] %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
    <% end %>
  </div>
  <% end %>
  <%= paginate @videos,params:{:param_page=>"page"}%>
<% end %>

app/views/searchs/show.html.erb
<h1>Youtube検索結果</h1>

  <% @youtube_data.items.each do |item| %>
  <% snippet = item.snippet %>
  <p><%= snippet.title %></p>
  <p><%= snippet.published_at %><%= snippet.channel_title %></p>
  <div><iframe width="560" height="315" src="https://www.youtube.com/embed/<%= item.id.video_id %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
<% end %>